Explanations of why we introduce topics
savvy-coders/sc-curriculum pull request #140
Opened 2021-08-16 18:03 UTC by cbrantley4

I've gotten started on this ticket. Let me know what you think

2021-08-17 23:21 UTC, JohanBester reviewed
Hello Cameron,

I have looked at the changes you are proposing. You have done a lot of work here. Thank you for your dedication..

I was wondering if it is totally necessary to comment on each Bullitt point in every section though?

I though the intent of the ticket was to just give a simple, 1 paragraph, reason for why we are learning the materials in a certain section. It was certainly not meant to write a reason for every bullet point... 
EG: Why are we learning about data data collections? Or why are we learning about Array methods? Or why are we learning about HTML or CSS? Or why do we have to Learn about SPAs?

I think by narrowing down the amount and number of comments,(1) it will be way less work, and (2) the comments can be more targeted in that they will cover a broader scope with less detailed. 
The detail belongs in the lesson, not the into paragraph that was meant to only outline what the class is about.
Else the opening outline is redundant, and more detail should be added into the lesson.

I feel we are trying to reinvent the wheel here, and "muddying the waters" with too much info before we even get into teaching the details of what the students should learn.

My opinions are aimed at reducing the work you are doing, and making the curiculum more maintainable.

2021-08-17 23:21 UTC, JohanBester commented on Section03/3.1-Functions.md
> +When a function is created it is necessary to define what the expected output is. This expected output is code that is only able to be used inside the function.
Hi Cameron,
In the old curriculum we had this phrase about scope...
" In JavaScript, scopes are created by code blocks and modules, like in a function. A variable defined inside a scope is accessible only within that scope, but inaccessible outside of it. "
Not sure if something like this is simpler in the context?

I was thinking that the current description could be confusing as the output that is returned from a function can be used elsewhere.

2021-08-17 23:21 UTC, JohanBester commented on Section03/3.2-DataCollections.md
> +Primitive Data Types refers to all pieces of data you will see in the JavaScript environment. You can create a collection of these pieces of data by grouping them as objects.
Don't want to be picky, but not all pieces of data one will see in JS are primitives.

2021-08-18 00:33 UTC, cbrantley4 commented on Section03/3.2-DataCollections.md
> +Primitive Data Types refers to all pieces of data you will see in the JavaScript environment. You can create a collection of these pieces of data by grouping them as objects.
I'm glad you're being picky!!

2021-08-18 13:51 UTC, matsinet requested changes

2021-08-18 13:51 UTC, matsinet commented on Section03/3.1-Functions.md
> +In JavaScript, scopes are created by code blocks and modules, like in a function. A variable defined inside a scope is accessible only within that scope, but inaccessible outside of it.
We need to update this to state the variable in parent scopes are available in child scopes.    It is accurate that variables are not available in child or sibling scopes.

2021-08-18 13:51 UTC, matsinet commented on Section03/3.2-DataCollections.md
> +JS Arrays and Objects are both collections of data. Each individual piece of data inside a JS Array can be identified by the index. Each individual piece of data inside a JS Object, however, is ident
I would remove the word value when stating the an object data is identified such as:
"identified by its key as the data"

2021-08-18 17:50 UTC, matsinet approved these changes
👍

2021-08-18 17:53 UTC, dadler89 approved these changes

2021-08-18 18:01 UTC, merged