Section2 AND Section3 updates
savvy-coders/sc-curriculum pull request #176
Opened 2021-11-19 03:40 UTC by JohanBester

Hi Folks,

Here is my combined PR for updates to section2 and section3 of the curriculum.

I also fixed any content errors I found during class.

One of the things I have done is to try and simplify the language -- using simpler expressions and shorter sentence with less complicated language structure.

I have done this because in both the last 2 cohorts there are people that are strong in English but have a desire to learn to code.

Kindly please review and let me know what changes I should make.

2021-11-19 15:02 UTC, matsinet requested changes
@JohanBester I have added comments

2021-11-19 15:10 UTC, JohanBester commented on Section02/2-Homework.md
> +1. Use the [Savvy-Coders Starter template repo](https://github.com/savvy-coders/savvy-starter) to _create a new GitHub repo for homework_ - name it something that indicates it is for **Savvy Coders H
Excellent suggestion. Will make that change.

2021-11-19 15:11 UTC, JohanBester commented on Section02/2.1-EssentialDevTools.md
> +**After cloning the Savvy Coders Starter template repo to your local machine, open it in VS Code.**
True. Thank you Matt! WIll add as well.

2021-11-19 15:12 UTC, JohanBester commented on Section02/2.2-JSdataTypeAndVariables.md
> +Over the next few weeks you will be exposed to a lot of new information and concepts. Please remember to breath and to be patient with yourself. You will probably be bad at programming for a time, ju
Ooops. sorry my bad.

2021-11-19 17:25 UTC, drod1107 submitted a review, later dismissed

2021-11-20 15:08 UTC, cbrantley4 submitted a review, later dismissed
Looks great!

2021-11-22 18:49 UTC, matsinet approved these changes

2021-11-22 18:49 UTC, mjwebb1993 approved these changes

2021-11-22 18:49 UTC, cbrantley4 approved these changes
Merge it

2021-11-22 18:50 UTC, merged