Updates to current syllabus
savvy-coders/sc-curriculum pull request #183
Opened 2021-12-04 13:33 UTC by cbrantley4

2021-12-04 19:45 UTC, matsinet requested changes

2021-12-04 19:45 UTC, matsinet commented on Section00/0-Syllabus.md
> +  <li>Manage long-term data storage via CRUD server and MongoDB database.</li>
Let's change CRUD to REST

2021-12-04 21:11 UTC, matsinet approved these changes

2021-12-04 22:14 UTC, JohanBester approved these changes

2021-12-06 18:13 UTC, mjwebb1993 approved these changes

2021-12-06 18:20 UTC, merged