Section6updates
savvy-coders/sc-curriculum pull request #211
Opened 2022-01-09 18:44 UTC by JohanBester

Here is a request to pull the Section 6 Updates into the development branch.

Please carefully review this work. A great deal many things were changed and there are probably issues that will need to be addressed and corrected.

Thank you.

2022-01-10 16:00 UTC, matsinet commented on Section06/6.1-SPAIntro.md
> +- **`lib`** represents an _optional_ **lib**rary of _JS modules_ which _export_ Functions, Classes, Objects, or Arrays that we might maybe possibly want to use in any of our "main" (`components`, `st
I would prefer if the `lib` folder was completely removed

2022-01-10 16:12 UTC, matsinet requested changes

2022-01-10 16:12 UTC, matsinet commented on Section06/6.1-SPAIntro.md
> +![Basic SPA File Structure](Resources/img/basic-SPA-file-structure.png)
did we move the images for the markdown into the Resources folder?   Is that consistent over the entire curriculum?

2022-01-10 16:12 UTC, matsinet commented on Section06/6.2-SPAComponents.md
> +import sharksImage from "/assets/IMG_20150708_133155453.jpg";
Were the quotes changed from single to double by a linter or by hand?   If by hand, why?

2022-01-10 16:12 UTC, matsinet commented on Section06/Activities/6.2-Activities/index.js
> +  Array.from(event.target.elements).forEach((el) => {
were the parens added manually or via linter?   My linter suggests that single parameters do not have parens?

2022-01-10 16:12 UTC, matsinet commented on Section06/Activities/finalRootIndex.js
> +  addEventListeners();
I would like to rename the addEventListeners function to afterRender in all curriculum

2022-01-10 18:30 UTC, JohanBester commented on Section06/6.1-SPAIntro.md
> +- **`lib`** represents an _optional_ **lib**rary of _JS modules_ which _export_ Functions, Classes, Objects, or Arrays that we might maybe possibly want to use in any of our "main" (`components`, `st
OK, will do!  :)

2022-01-10 18:31 UTC, JohanBester commented on Section06/6.2-SPAComponents.md
> +import sharksImage from "/assets/IMG_20150708_133155453.jpg";
Darn, I'm going to kill al the linters..

2022-01-10 23:15 UTC, JohanBester commented on Section06/6.1-SPAIntro.md
> +![Basic SPA File Structure](Resources/img/basic-SPA-file-structure.png)
The images have been moved to the correct space

2022-01-10 23:36 UTC, JohanBester commented on Section06/Activities/6.2-Activities/index.js
> +  Array.from(event.target.elements).forEach((el) => {
This has been corrected directly in GitHub

2022-01-12 01:44 UTC, cbrantley4 approved these changes
Looks good to me!

2022-01-12 16:33 UTC, matsinet approved these changes
Merge it

2022-01-12 18:40 UTC, merged