Scc 182 GRID additions
savvy-coders/sc-curriculum pull request #261
Opened 2022-03-19 19:16 UTC by JohanBester

Hello Folks,

I have made the GRID additions to the curriculum in section 6.1
I have ironed out a few things in 6.2 & 6.3 that have changed due to changes in 6.1

Apart from those I've made a few additions to the Addendum section as well.

Kindly, please review and add your comments on these updates and additions.

Thanks!

2022-03-20 01:39 UTC, cbrantley4 requested changes
I must have missed the discussion on changing the file name from store to state. Can we discuss this on Monday?

2022-03-20 01:39 UTC, cbrantley4 commented on Section06/6-Homework.md
> +- In your capstone repo create the folder structure for an SPA -- `components`, `views`, and `state`.
I must have missed something here. But aren't we keeping the folder name as store?

2022-03-21 16:12 UTC, matsinet commented on Section06/6-Homework.md
> +- In your capstone repo create the folder structure for an SPA -- `components`, `views`, and `state`.
Agreed, `state` should be updated to `store`

2022-03-21 16:14 UTC, matsinet commented on Section06/6-Homework.md
> +- Remember to build your aggregators (`index.js`) in `components`, `views`, and `state`
`state` should be `store`

2022-03-21 16:17 UTC, matsinet commented on Section06/6.3-SPAState.md
> +3. Inside of `state`, create the following JS files:
`state` should be `store`

2022-03-21 17:54 UTC, matsinet requested changes

2022-03-21 17:54 UTC, matsinet commented on Section06/6.3-SPAState.md
> +2. Let's begin to construct our state by creating a directory named `state` in the root level of our repo.
`state` should be updated to `store`

2022-03-21 17:54 UTC, matsinet commented on Section06/6.3-SPAState.md
> +6. Inside `state/index.js`, let's aggregate each of our modules with one-line import/export statements.
`state` should be updated to `store`

2022-03-21 17:54 UTC, matsinet commented on Section06/6.3-SPAState.md
> +   import * as store from "./state";
`state` should be updated to `store`

2022-03-21 17:54 UTC, matsinet commented on Section06/6.3-SPAState.md
> +7. Now our state modules are prepped and collected and ready to import. In our root `index.js`, let's `import` our state modules as a module Object named `state`.
`state` should be updated to `store`

2022-03-21 17:54 UTC, matsinet commented on Section06/6.3-SPAState.md
> +   - Unlike our header and "main" section of our site, we want our navigation bar to remain similar no matter which view we are rendering. Let's bypass the specific piece of state being passed in to
`state` should be updated to `store`

2022-03-21 17:54 UTC, matsinet commented on Section06/6.3-SPAState.md
> +       ${Nav(state.Links)}
`state` should be updated to `store`

2022-03-21 17:54 UTC, matsinet commented on Section06/6.3-SPAState.md
> +   render(state.Home);
`state` should be updated to `store`

2022-03-21 17:54 UTC, matsinet commented on Section06/6.3-SPAState.md
> +     In our store let's create a `state/Links.js` file, and copy the following code into it:
`state` should be updated to `store`

2022-03-28 13:37 UTC, matsinet requested changes

2022-03-28 13:37 UTC, matsinet commented on Section06/6.3-SPAState.md
> +   function render(st) {
`st` needs to be replaced with `state` in the render function (and all component files)

2022-03-28 13:37 UTC, matsinet commented on Section06/6.3-SPAState.md
> +   - In `components/Header.js`, add a parameter to our exported function that represents a piece of state. Inside our `<h1>`, replace "Example SPA" with the "variable" `store.header`
`store` should be `state` here as it is localized to the component

2022-03-28 17:46 UTC, matsinet approved these changes

2022-03-28 17:46 UTC, mjwebb1993 approved these changes
Looks good 👍

2022-03-28 17:46 UTC, cbrantley4 approved these changes
Merge

2022-03-28 17:46 UTC, merged