SCC 262
savvy-coders/sc-curriculum pull request #267
Opened 2022-03-23 01:39 UTC by H-Matzy

Had to rebase from an updated version of development, made some additional changes to where we access params data

2022-03-23 13:25 UTC, matsinet requested changes

2022-03-23 13:25 UTC, matsinet commented on Section07/7.2-APIsAndAxios1.md
> +Weather in ${store.weather.city} ${kelvinToFahrenheit(store.weather.temp)}F, feels
In this case because this instance is in the view and not the main index.js needs to be `state` instead of `store`

2022-03-23 13:25 UTC, matsinet commented on Section07/7.2-APIsAndAxios1.md
> +       const view = params && params.data.hasOwnProperty("view") ? capitalize(params.data.view) : "Home";
Let's update this to be consistent with the previous check and look like the following:
`const view = params && params.data.hasOwnProperty("view") ? capitalize(params.data.view) : "Home";`

2022-03-23 13:25 UTC, matsinet commented on Section07/7.2-APIsAndAxios1.md
> +    const view = params && params.data.hasOwnProperty("view") ? capitalize(params.data.view) : "Home";
Let's update this to be consistent with the previous check and look like the following:
`const view = params && params.data.hasOwnProperty("view") ? capitalize(params.data.view) : "Home";`

2022-03-23 17:18 UTC, cbrantley4 approved these changes
Good to go

2022-03-27 14:40 UTC, H-Matzy commented
Ready for Merge

2022-03-28 13:30 UTC, matsinet requested changes
All looks good except the one correction

2022-03-28 13:30 UTC, matsinet commented on Section06/6.3-SPAState.md
> +   - In `components/Header.js`, add a parameter to our exported function that represents a piece of state. Inside our `<h1>`, replace "Example SPA" with the "variable" `store.Header`
@H-Matzy  this still needs to be `state.header` in the component as it is accessing the `header` key in the view `state` within the component itself.  As example in the Home.js state file within the store folder
```
export default {
  header: "My Home Page",
  view: "Home",
  weather: {},
};
```

2022-03-28 14:33 UTC, cbrantley4 submitted a review, later dismissed
Merge it after Matt's update

2022-03-29 23:35 UTC, matsinet approved these changes

2022-03-29 23:36 UTC, merged