Update 2.3-JSOperatorsAndFlowControl.md
savvy-coders/sc-curriculum pull request #281
Opened 2022-04-15 00:00 UTC by mjwebb1993

Fixing a very simple typo

2022-04-15 13:50 UTC, matsinet commented
@mjwebb1993 this PR should go against `development` and not `master`
The change is not urgent enough to push against `master` mid cohort.
Besides if it were going against `master` then a second PR would be required to bring `development` up to speed as well

2022-04-15 13:52 UTC, matsinet requested changes
@mjwebb1993 this PR should go against development and not master
The change is not urgent enough to push against master mid cohort.
Besides if it were going against master then a second PR would be required to bring development up to speed as well

2022-04-17 20:46 UTC, cbrantley4 approved these changes
Looks good!

2022-04-18 17:18 UTC, matsinet approved these changes

2022-04-18 17:20 UTC, merged