updated sec 6.3
savvy-coders/sc-curriculum pull request #319
Opened 2022-07-13 18:05 UTC by JohanBester

Hello Folks,

I updates section 6.3 according to the notes in ticket #296

Kindly please review these changes and comment as needed.

Thanks!

2022-07-13 18:28 UTC, matsinet requested changes

2022-07-13 18:28 UTC, matsinet commented on Section06/6.3-SPAState.md
> +5. Now our state modules are prepped and collected and ready to import. In our root `index.js`, let's `import` our state modules as a module Object named `store`.
this should be item 6

2022-07-14 02:48 UTC, mjwebb1993 requested changes
I can touch up on this in the slack channel, but would it be possible to implement an additional change to this PR? I think the very last step in 6.3, which says to remove the following code from the router hook:
`document.querySelectorAll("nav a").forEach((navLink) =>
  navLink.addEventListener("click", (event) => {
    event.preventDefault();
    render(state[event.target.title]);
  })
);`

I don't believe this code is necessary as we did not have this in our code, at least not at the beginning of the night
![000098](https://user-images.githubusercontent.com/61995762/178887362-f50424ee-e33d-4300-a9cd-e05702ee9006.png)

2022-07-14 02:54 UTC, JohanBester commented on Section06/6.3-SPAState.md
> +5. Now our state modules are prepped and collected and ready to import. In our root `index.js`, let's `import` our state modules as a module Object named `store`.
Hi Matt, thanks for catching that. I fixed up the order and made the number changes.  Thank you.

2022-07-14 03:12 UTC, JohanBester commented
Hello Gents,
I have made the changes you suggested.

Please review those and let me know if that works for you.
I think I got it right this time 😁

2022-07-25 17:41 UTC, matsinet submitted a review, later dismissed

2022-07-25 21:17 UTC, mjwebb1993 approved these changes

2022-07-25 22:22 UTC, merged