SCC-327 switch case curly brackets
savvy-coders/sc-curriculum pull request #328
Opened 2022-08-01 22:55 UTC by matsinet

2022-08-01 23:26 UTC, JohanBester reviewed
Matt, 
Regarding that PR you made: As far as I know and have tested, when there is a code block in a case that instantiates the same variable over and over again, it needs to be scoped.
Just, as we are doing in the curriculum (below) restating "let message = " in every case.
Here is the link on MDN that explains it and why it breaks if there is no Lexical scoping in the case statements.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/switch#lexical_scoping

`  const errand = "Going Shopping";

  switch (errand) {
    case "Going to the Dentist": {
      let message = "I hate going to the dentist";
      console.log(message);
      break;
    }
    case "Going Shopping": {
      let message = "I love to shop";
      console.log(message);
      break;
    }
    case "Going to the movies": {
      let message = "I love chick-flicks";
      console.log(message);
      break;
    }
    case "Going to the Bank": {
      let message = "Money makes the world go round!";
      console.log(message);
      break;
    }
    case "Going to the gym": {
      let message = "Healthy bodies host healthy minds!";
      console.log(message);
      break;
    }
    default: {
      console.log("No errand");
      break;
    }
  }
`

2022-08-02 13:31 UTC, matsinet commented
@JohanBester  You have a point about the redeclaration of the variable but I ask why are we redeclaring the same variable?
Why not declare it once at the top and just reassign in each switch or if you were going to declare it in each case and since it is never reassigned within the case it should be a const instead of a let.

Just trying to have a discussion, either way my PR code is not correct.  Which way should be go to resolve the issue.

```
  let message = "No errand";

  switch (errand) {
    case "Going to the Dentist":
      message = "I hate going to the dentist";
      console.log(message);
      break;
    case "Going Shopping":
      message = "I love to shop";
      console.log(message);
      break;
    case "Going to the movies":
      message = "I love chick-flicks";
      console.log(message);
      break;
    case "Going to the Bank":
      message = "Money makes the world go round!";
      console.log(message);
      break;
    case "Going to the gym":
      message = "Healthy bodies host healthy minds!";
      console.log(message);
      break;
    default:
      console.log(message);
      break;
  }
```

```
  switch (errand) {
    case "Going to the Dentist": {
      const message = "I hate going to the dentist";
      console.log(message);
      break;
    }
    case "Going Shopping": {
      const message = "I love to shop";
      console.log(message);
      break;
    }
    case "Going to the movies": {
      const message = "I love chick-flicks";
      console.log(message);
      break;
    }
    case "Going to the Bank": {
      const message = "Money makes the world go round!";
      console.log(message);
      break;
    }
    case "Going to the gym": {
      const message = "Healthy bodies host healthy minds!";
      console.log(message);
      break;
    }
    default: {
      console.log("No Errand");
      break;
    }
  }
```

2022-08-03 17:18 UTC, mjwebb1993 approved these changes

2022-08-03 17:29 UTC, mjwebb1993 requested changes
option 2

2022-08-03 17:54 UTC, mjwebb1993 approved these changes

2022-08-03 17:55 UTC, merged